In [ ]:
# default_exp dems

In [ ]:
# export
from dataclasses import dataclass
from pathlib import Path

import xarray as xr

from trex_diviner_pipeline import core


class LOLA_DEM:
    root = Path("/luna4/maye/dems")
    fnames = {
        "data": "ldem_128_jp2.tif",
        "slope": "ldem_128_slope_percent.tif",
        "aspect": "ldem_128_aspect.tif",
    }

    def __init__(self, lat_limit=None):
        self.lat_limit = lat_limit

        # assign name attributes data/slope/aspect:
        for key, fname in self.fnames.items():
            setattr(self, f"{key}_fpath", self.root / fname)
            setattr(self, key, core.read_raster_image(self.root/fname).squeeze())
            
        lats = np.linspace(-90, 90, len(self.data.y))
        lons = np.linspace(-180, 180, len(self.data.x))
        for key in self.fnames.keys():
            o = getattr(self, key)
            o = o.assign_coords(lat=('y', lats))
            o = o.assign_coords(lon=('x', lons))
            o = o.swap_dims({'y':'lat', 'x':'lon'})
            setattr(self, key, o)

In [ ]:
dem = LOLA_DEM()

AttributeError: module 'trex_diviner_pipeline.core' has no attribute 'read_raster_image'

In [ ]:
dem.data

<xarray.DataArray (y: 23040, x: 46080)>
dask.array<getitem, shape=(23040, 46080), dtype=int16, chunksize=(2048, 4096), chunktype=numpy.ndarray>
Coordinates:
    band     int64 1
  * y        (y) float64 2.729e+06 2.729e+06 2.729e+06 ... -2.729e+06 -2.729e+06
  * x        (x) float64 -5.458e+06 -5.458e+06 ... 5.458e+06 5.458e+06
    lat      (y) float64 -90.0 -89.99 -89.98 -89.98 ... 89.98 89.98 89.99 90.0
    lon      (x) float64 -180.0 -180.0 -180.0 -180.0 ... 180.0 180.0 180.0 180.0
Attributes:
    transform:                  (236.9011752, 0.0, -5458203.076608, 0.0, -236...
    crs:                        +proj=eqc +lat_ts=0 +lat_0=0 +lon_0=0 +x_0=0 ...
    res:                        (236.9011752, 236.9011752)
    is_tiled:                   1
    nodatavals:                 (-32768.0,)
    scales:                     (0.5,)
    offsets:                    (1737400.0,)
    AREA_OR_POINT:              Area
    DATA_SET_ID:                "LRO-L-LOLA-4-GDR-V1.0"
    INSTRUMENT_ID:              "LOLA"
    INSTRUMENT_NAME:            "LUNAR ORBITER LASER ALTIMETER"
    PRODUCER_INSTITUTION_NAME:  "GODDARD SPACE FLIGHT CENTER"
    PRODUCT_CREATION_TIME:      2017-09-15
    PRODUCT_ID:                 "LDEM_128"
    START_TIME:                 2009-07-13T17:33:17.246
    STOP_TIME:                  2016-11-29T05:48:19
    TARGET_NAME:                MOON

In [ ]:
dem.data.coords

Coordinates:
    band     int64 1
  * y        (y) float64 2.729e+06 2.729e+06 2.729e+06 ... -2.729e+06 -2.729e+06
  * x        (x) float64 -5.458e+06 -5.458e+06 ... 5.458e+06 5.458e+06
    lat      (y) float64 -90.0 -89.99 -89.98 -89.98 ... 89.98 89.98 89.99 90.0
    lon      (x) float64 -180.0 -180.0 -180.0 -180.0 ... 180.0 180.0 180.0 180.0

In [ ]:
# check dtypes
assert isinstance(dem.data_fpath, Path)
assert isinstance(dem.slope_fpath, Path)
assert isinstance(dem.aspect_fpath, Path)
assert isinstance(dem.data, xr.DataArray)

In [ ]:
# check squeezing and resulting dims
assert dem.data.ndim == 2
assert dem.slope.ndim == 2

In [ ]:
s = slice(80, -80)
s

slice(80, -80, None)

In [ ]:
dem.data

<xarray.DataArray (y: 23040, x: 46080)>
dask.array<getitem, shape=(23040, 46080), dtype=int16, chunksize=(2048, 4096), chunktype=numpy.ndarray>
Coordinates:
    band     int64 1
  * y        (y) float64 2.729e+06 2.729e+06 2.729e+06 ... -2.729e+06 -2.729e+06
  * x        (x) float64 -5.458e+06 -5.458e+06 ... 5.458e+06 5.458e+06
    lat      (y) float64 -90.0 -89.99 -89.98 -89.98 ... 89.98 89.98 89.99 90.0
    lon      (x) float64 -180.0 -180.0 -180.0 -180.0 ... 180.0 180.0 180.0 180.0
Attributes:
    transform:                  (236.9011752, 0.0, -5458203.076608, 0.0, -236...
    crs:                        +proj=eqc +lat_ts=0 +lat_0=0 +lon_0=0 +x_0=0 ...
    res:                        (236.9011752, 236.9011752)
    is_tiled:                   1
    nodatavals:                 (-32768.0,)
    scales:                     (0.5,)
    offsets:                    (1737400.0,)
    AREA_OR_POINT:              Area
    DATA_SET_ID:                "LRO-L-LOLA-4-GDR-V1.0"
    INSTRUMENT_ID:              "LOLA"
    INSTRUMENT_NAME:            "LUNAR ORBITER LASER ALTIMETER"
    PRODUCER_INSTITUTION_NAME:  "GODDARD SPACE FLIGHT CENTER"
    PRODUCT_CREATION_TIME:      2017-09-15
    PRODUCT_ID:                 "LDEM_128"
    START_TIME:                 2009-07-13T17:33:17.246
    STOP_TIME:                  2016-11-29T05:48:19
    TARGET_NAME:                MOON

In [ ]:
dem.data.coords[]

Coordinates:
    band     int64 1
  * y        (y) float64 2.729e+06 2.729e+06 2.729e+06 ... -2.729e+06 -2.729e+06
  * x        (x) float64 -5.458e+06 -5.458e+06 ... 5.458e+06 5.458e+06
    lat      (y) float64 -90.0 -89.99 -89.98 -89.98 ... 89.98 89.98 89.99 90.0
    lon      (x) float64 -180.0 -180.0 -180.0 -180.0 ... 180.0 180.0 180.0 180.0

In [ ]:
da.sel(lat=slice(-80, 80), drop=True).compute()

<xarray.DataArray (y: 23040, x: 46080)>
array([[-100,  -96,  -91, ..., -110, -107, -104],
       [-104,  -99,  -93, ..., -113, -110, -107],
       [-112, -109, -105, ..., -117, -114, -113],
       ...,
       [2413, 2405, 2399, ..., 2433, 2428, 2420],
       [2488, 2469, 2454, ..., 2574, 2542, 2511],
       [2494, 2481, 2468, ..., 2529, 2520, 2508]], dtype=int16)
Coordinates:
    band     int64 1
  * y        (y) float64 2.729e+06 2.729e+06 2.729e+06 ... -2.729e+06 -2.729e+06
  * x        (x) float64 -5.458e+06 -5.458e+06 ... 5.458e+06 5.458e+06
    lon      (x) float64 -180.0 -180.0 -180.0 -180.0 ... 180.0 180.0 180.0 180.0
  * lat      (lat) float64 -80.0 -79.99 -79.98 -79.98 ... 79.98 79.98 79.99 80.0
Attributes:
    transform:                  (236.9011752, 0.0, -5458203.076608, 0.0, -236...
    crs:                        +proj=eqc +lat_ts=0 +lat_0=0 +lon_0=0 +x_0=0 ...
    res:                        (236.9011752, 236.9011752)
    is_tiled:                   1
    nodatavals:                 (-32768.0,)
    scales:                     (0.5,)
    offsets:                    (1737400.0,)
    AREA_OR_POINT:              Area
    DATA_SET_ID:                "LRO-L-LOLA-4-GDR-V1.0"
    INSTRUMENT_ID:              "LOLA"
    INSTRUMENT_NAME:            "LUNAR ORBITER LASER ALTIMETER"
    PRODUCER_INSTITUTION_NAME:  "GODDARD SPACE FLIGHT CENTER"
    PRODUCT_CREATION_TIME:      2017-09-15
    PRODUCT_ID:                 "LDEM_128"
    START_TIME:                 2009-07-13T17:33:17.246
    STOP_TIME:                  2016-11-29T05:48:19
    TARGET_NAME:                MOON

In [ ]:
xr.open_rasterio?

Signature:
xr.open_rasterio(
    filename,
    parse_coordinates=None,
    chunks=None,
    cache=None,
    lock=None,
)
Docstring:
Open a file with rasterio (experimental).

This should work with any file that rasterio can open (most often:
geoTIFF). The x and y coordinates are generated automatically from the
file's geoinformation, shifted to the center of each pixel (see
`"PixelIsArea" Raster Space
<http://web.archive.org/web/20160326194152/http://remotesensing.org/geotiff/spec/geotiff2.5.html#2.5.2>`_
for more information).

You can generate 2D coordinates from the file's attributes with::

    from affine import Affine
    da = xr.open_rasterio('path_to_file.tif')
    transform = Affine.from_gdal(*da.attrs['transform'])
    nx, ny = da.sizes['x'], da.sizes['y']
    x, y = np.meshgrid(np.arange(nx)+0.5, np.arange(ny)+0.5) * transform


Parameters
----------
filename : str, rasterio.DatasetReader, or rasterio.WarpedVRT
    Path to the file to open. Or already open rasterio dataset.


In [ ]:
array = xr.DataArray(
    np.random.randn(2, 3), coords=[("x", ["a", "b"]), ("y", [0, 1, 2])]
)
array

<xarray.DataArray (x: 2, y: 3)>
array([[ 0.98246975,  0.88500814, -0.70164571],
       [-0.03143242, -0.22037288,  0.6166981 ]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 0 1 2

In [ ]:
array.stack(z=("x", "y")).unstack("z")

<xarray.DataArray (x: 2, y: 3)>
array([[ 0.98246975,  0.88500814, -0.70164571],
       [-0.03143242, -0.22037288,  0.6166981 ]])
Coordinates:
  * x        (x) object 'a' 'b'
  * y        (y) int64 0 1 2

In [ ]:
dem.data[:3, :3].compute()

<xarray.DataArray (y: 3, x: 3)>
array([[-100,  -96,  -91],
       [-104,  -99,  -93],
       [-112, -109, -105]], dtype=int16)
Coordinates:
    band     int64 1
  * y        (y) float64 2.729e+06 2.729e+06 2.729e+06
  * x        (x) float64 -5.458e+06 -5.458e+06 -5.458e+06
Attributes:
    transform:                  (236.9011752, 0.0, -5458203.076608, 0.0, -236...
    crs:                        +proj=eqc +lat_ts=0 +lat_0=0 +lon_0=0 +x_0=0 ...
    res:                        (236.9011752, 236.9011752)
    is_tiled:                   1
    nodatavals:                 (-32768.0,)
    scales:                     (0.5,)
    offsets:                    (1737400.0,)
    AREA_OR_POINT:              Area
    DATA_SET_ID:                "LRO-L-LOLA-4-GDR-V1.0"
    INSTRUMENT_ID:              "LOLA"
    INSTRUMENT_NAME:            "LUNAR ORBITER LASER ALTIMETER"
    PRODUCER_INSTITUTION_NAME:  "GODDARD SPACE FLIGHT CENTER"
    PRODUCT_CREATION_TIME:      2017-09-15
    PRODUCT_ID:                 "LDEM_128"
    START_TIME:                 2009-07-13T17:33:17.246
    STOP_TIME:                  2016-11-29T05:48:19
    TARGET_NAME:                MOON

In [ ]:
dem.slope[:3, :3].compute()

<xarray.DataArray (y: 3, x: 3)>
array([[1.793997 , 2.2829463, 2.175541 ],
       [3.103708 , 3.3983035, 3.891726 ],
       [4.2053103, 5.0741897, 6.1411304]], dtype=float32)
Coordinates:
    band     int64 1
  * y        (y) float64 2.729e+06 2.729e+06 2.729e+06
  * x        (x) float64 -5.458e+06 -5.458e+06 -5.458e+06
Attributes:
    transform:      (236.9011752, 0.0, -5458203.076608, 0.0, -236.9011752, 27...
    crs:            +proj=eqc +lat_ts=0 +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +R=17...
    res:            (236.9011752, 236.9011752)
    is_tiled:       0
    nodatavals:     (-9999.0,)
    scales:         (1.0,)
    offsets:        (0.0,)
    AREA_OR_POINT:  Area

In [ ]:
104/99

1.0505050505050506

In [ ]:
109/99

1.101010101010101